### ISSUE TITLE
[Packaging | License] - Add a license to the project

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/reana-jupyterlab-extension#3]
After having investigated and getting familiarised with
 - Proprietary / non-commercial licenses
 - Copyleft licenses
 - Permissive and open licenses

**Comment by rubenperezm** [comment]
A permissive free software license should be used (Apache License 2.0 seems a good choice)

**Comment by rubenperezm** [comment]
> Any scenario in where a copyleft license could be useful or needed ?

Permissive permits proprietary derivative works. If we want our project to be 100% free (and guarantee that anyone who uses this code to make their code open), we may use a copyleft license (e.g., GNU GPL).

> Also, are you familiarised with the re-licensing of a repository / project ? Please investigate under which circumstances this can be done and by whom.

It depends on the original license and the final license. The original license of the extension template is BSD (permissive), so it could be done. With copyleft licenses this would be more difficult. In addition, when we use the `copier` command in the tutorial, it creates the license with the "extension author name" (me), so I think I can modify the license.
