### ISSUE TITLE
[Frontend] - Develop Login tab

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/reana-jupyterlab-extension#6]
Would allow connecting with the REANA-VRE service.

Connect in the same way as Reana does: by specifying the reana server url and the reana access token

**Comment by rubenperezm** [comment]
Would it be necessary to keep the server name and the access token after refreshing the page?

**Comment by rubenperezm** [comment]
I'm not facing any errors at all, I just wanted to know if I should implement this or not. Understood ;)

**Comment by rubenperezm** [comment]
> Would it be necessary to keep the server name and the access token after refreshing the page?

It is implemented now. I am using a file under the `/tmp` directory in the server to store the credentials. It is overwritten when the user tries to connect with other credentials, and is read after refreshing the page (if the file does not exist, the values are empty strings).
